#_____                 _                   _______ _____
#|  __ \               | |                 |__   __|  __ \
#| |__) |__ _ _ __   __| | ___  _ __ ___      | |  | |__) |
#|  _  // _` | '_ \ / _` |/ _ \| '_ ` _ \     | |  |  ___/
#| | \ \ (_| | | | | (_| | (_) | | | | | |    | |  | |
#|_|  \_\__,_|_| |_|\__,_|\___/|_| |_| |_|    |_|  |_|
#By: Kubajsa

#The distance from 0 0 you want the player to be able to teleport to.
border: 1000

#Cooldown for the /rtp command; set to 0 for no cooldown
cooldown: 15

#Should the plugin rtp players that joined for their first time
rtp-on-first-join: false

#If the plugin should check for updates on startup, this is recommended to be enabled
update-checker: true

#--Messages--
#At messages that are marked with a "%" you can use '%player%' as a placeholder for the player
Messages:
  #The message you see when you get teleported
  tp-message: "&6You were teleported to a random location"
  #Message that the player that performed the command /rtp <player> will receive. %
  tp-message-sender: "&6You teleported &c%player% &6to a random location"
  #The message you see when you execute the /rtp @everyone command
  tp-everyone-message: "&6Teleporting everyone on the server"
  #Unknown command message
  unknown-command: "&cUnknown command, try /rtplugin help"
  #Not enough permission
  no-permission: "&cInsufficient permission."
  #Canceled teleport because you aren't in the overworld
  player-not-in-overworld: "&cYou couldn't be teleported because you are not in the overworld"


#--Titles--
Titles:
  #Should a title appear when generating a location? Yes = true; No = false
  enabled: true
  #Title message
  generating-title: "&bTeleporting you to a random location"
  #Subtitle message
  generating-subtitle: "&6Generating a safe location"

#If enabled the plugin will give the player resistance after rtping
Invincibility:
  enabled: true
  potion-seconds: 5
  potion-amplifier: 3

#Should the plugin play a sound when teleporting a player
Sounds:
  enabled: true
  #Full list of sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  sound: BLOCK_NOTE_BLOCK_CHIME

#Should the plugin spawn particles upon teleportation
Particles:
  enabled: true
  #Full list of particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  particle: FIREWORKS_SPARK
  count: 1