#_____                 _                   _______ _____
#|  __ \               | |                 |__   __|  __ \
#| |__) |__ _ _ __   __| | ___  _ __ ___      | |  | |__) |
#|  _  // _` | '_ \ / _` |/ _ \| '_ ` _ \     | |  |  ___/
#| | \ \ (_| | | | | (_| | (_) | | | | | |    | |  | |
#|_|  \_\__,_|_| |_|\__,_|\___/|_| |_| |_|    |_|  |_|
#By: Kubajsa
#Need help with the plugin? Feel free to join the Discord server
#https://discord.gg/M83rMvrG6H


#Default border
#If you don't have a set border for a specific world it will use this
border: 1000

#Always RTP Players to this world
Force-default-world:
  enabled: false
  #Name of the world you want your players to be ALWAYS RTP'd to
  world-name: world


#Cooldown for the /rtp command
#Set to 0 for no cooldown
Cooldown:
  #Cooldown in seconds
  seconds: 18000
  #In what format should be the remaining cooldown displayed
  #HOURS - Shows in hours if possible
  #MINUTES - Shows in minutes if possible
  #SECONDS - Always shows in seconds
  #AUTO - Automatically decides the best type to use (recommended)
  msg-format-type: AUTO
  Messages:
    hour: "hour(s)"
    minute: "minute(s)"
    second: "second(s)"

Countdown:
  enabled: true
  seconds: 5
  #Should the plugin count down in chat when RTP'ing
  #ie.
  #Teleporing in 5 seconds
  #Teleporing in 4 seconds
  #...........
  countdown-message: true

Rtp-settings:
  #Max attempts to generate location
  max-attempts: 30
  Confirm-gui:
    #Set to true if you want players to confirm their /rtp command in a GUI
    enabled: false
    #Title of the GUI **USE COLOR CODES**
    title: "&aConfirm RTP"
    #Confirm item material
    confirm-item: EMERALD_BLOCK
    #Cancel item material
    cancel-item: REDSTONE_BLOCK

  World-gui:
    #If enabled, when a player executes /rtp the plugin will show a GUI with the option to pick the world
    enabled: false
    #Title of the World GUI
    gui-title: "§aPick the world"
    Slots:
      #You have three slots in the World GUI
      one:
        #enabled - If it should appear in the World GUI
        enabled: true
        #world-name - The name of the world
        world-name: world
        #title - The title of the Item
        title: "§aRTP to world: world"
        #The item material
        material: GRASS_BLOCK
      two:
        enabled: true
        world-name: world
        title: "§aRTP to world: world"
        material: GRASS_BLOCK
      three:
        enabled: true
        world-name: world
        title: "§aRTP to world: world"
        material: GRASS_BLOCK

#RTP Settings for specific worlds

#--Template--
#Worlds:
#  world-name:
#    disabled: false
#    border: 10000
#  another-world:
#    disabled: true
#    border: 100
Worlds:
  #Nether World name: world_nether
  #End World name: world_the_end
  world:
    #disabled - Should RTP be disabled in this world
    disabled: false
    #border - Border in this world
    border: 1000
#  pvp:
#    disabled: true
#    border: 10
#  build:
#    disabled: false
#    border: 10000

#Should the plugin rtp players that joined for their first time
rtp-on-first-join: false


#If players that have the permission randomTp.rtp.onDeath should be rtp'd on death
rtp-on-death: false


#If the plugin should check for updates on startup, this is recommended to be enabled
update-checker: true


#Vault settings
Vault:
  enabled: false
  rtp-price: 100


#Biome blacklist settings
Biome-blacklist:
  enabled: true
  #Full list of biomes https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html (1.16.5)
  biomes:
    - OCEAN


#--Signs--
Signs:
  #If you want to enable RTP signs
  enabled: true
  Lines:
    #What text should be on the signs
    #!!! If you don't use color codes (ex: &a &b &e) on signs players without the permission could create RTP signs !!!
    one: "&a[RandomTP]"
    two: "&bClick to RTP!"
    three: ""
    four: ""


#--Titles--
Titles:
  #Should players see titles when being teleported
  enabled: true
  #Title message
  generating-title: "&bTeleporting you to a random location"
  #Subtitle message
  generating-subtitle: "&6Generating a safe location"


#If enabled the plugin will give the player resistance after rtp'ing
Invincibility:
  enabled: true
  potion-seconds: 5
  potion-amplifier: 3


#Should the plugin play a sound when teleporting a player
Sounds:
  enabled: true
  #Full list of sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html (1.16.5)
  sound: BLOCK_NOTE_BLOCK_CHIME


#Should the plugin spawn particles upon teleportation
Particles:
  enabled: true
  #Full list of particles: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html (1.16.5)
  particle: FIREWORKS_SPARK
  count: 1


#--Messages--
#Placeholders:
# %player% - Player's name
# %left% - Time left
#You can only use placeholders in some messages
Messages:
  #The message you see when you get teleported
  tp-message: "&6You were teleported to a random location"
  #Message that the player that executed the command /rtp <player> will receive.
  tp-message-sender: "&6You teleported &c%player% &6to a random location"
  #Message when you RTP someone to a specific biome
  tp-message-sender-biome: "&6You teleported &c%player% &6to a random location in the biome &c%biome%"
  #The message you see when you execute the /rtp @everyone command
  tp-everyone-message: "&6Teleporting everyone on the server"
  #Message when the world you try to rtp in is disabled
  world-disabled-message: "&cRTP is disabled in this world!"
  #Unknown command message
  unknown-command: "&cUnknown command, try /rtplugin help"
  #Not enough permission
  no-permission: "&cInsufficient permission."
  #If player doesn't have enough money to /rtp
  not-enough-money: "&cYou do not have enough money to do that!"
  #Successful transaction message
  took-money-message: "&a$%amount% has been taken from your account"
  #RTP Sign creation message
  sign-create: "&6Successfully created an RTP sign"
  #When an RTP sign is broken
  sign-break: "&6Successfully removed an RTP sign"
  #Cooldown message, %left% is for example 8 hour(s), 13 second(s), 1 minute(s) etc.
  cooldown-message: "&6You have a cooldown of &b%left%!"
  #Message when the plugin couldn't generate a location
  couldnt-generate-message: "&cCouldn't generate a safe location! Please try again"
  #Player tries to remove a sign while not shifting
  need-to-shift: "&cYou need to &6shift &cif you want to remove the sign"
  #Message the player sees when the countdown starts
  #Use %count% as a placeholder for the countdown timer lenght in seconds
  countdown-message: "&6Teleporting in %count% seconds... &4Do not move or take damage!"
  #Counting down message when RTP'ing
  #Use %time% as a placeholder for seconds remaining
  counting-down-message: "&6Teleporting in %time% seconds"
  #Message when RTP gets cancelled
  teleportation-cancelled-message: "&4Cancelled teleportation!"
  #Wrong biome name was used when /rtp'ing
  wrong-biome-name: "&cCouldn't find that biome!"
