name: Randomtp
version: ${project.version}
main: me.jakub.randomtp.Randomtp
api-version: 1.16
description: This is a /rtp plugin
commands:
  rtp:
    description: Randomly teleports the player to a random location
    aliases: wild
    usage: /<command> [player|@everyone]
  rtplugin:
    description: Main RandomTP plugin command
    usage: /<command> <help|setborder|reload> [number]