name: Randomtp
version: ${project.version}
main: me.jakub.randomtp.Randomtp
author: Kubajsa
api-version: 1.13
description: Highly customizable 1.13-1.16 RTP plugin
softdepend: [Vault, GriefPrevention, WorldGuard, Towny, RedProtect, ProtectionStones]
commands:
  rtp:
    description: Teleports the player to a random location
    aliases: wild
    usage: /<command> [player|@everyone|test] [world] [tier|biome]
  rtplugin:
    description: Main RandomTP plugin command
    usage: /<command> <help|setborder|reload> [number|commands|permissions]
permissions:
  randomTp.rtp:
    description: Allows you to /rtp
    default: true
  randomTp.rtp.others:
    description: Allows you to /rtp other players
  randomTp.rtp.everyone:
    description: Allows you to /rtp @everyone
  randomTp.rtp.onDeath:
    description: Allows you rtp on death
  randomTp.setborder:
    description: Allows you to set the RTP border
  randomTp.reload:
    description: Allows you to reload the plugin
  randomTp.cooldown.bypass:
    description: Allows you to bypass the cooldown
  randomTp.price.bypass:
    description: Bypass RTP price
  randomTp.countdown.bypass:
    description: Bypass countdown
  randomTp.sign.use:
    description: Use RTP signs
    default: true
  randomTp.sign.create:
    description: Create RTP signs
  randomTp.sign.break:
    description: Break RTP signs
  randomTp.rtp.test:
    description: Test RTP without actually teleporting
